### PR TITLE
Handle rpminspect.yaml, rpminspect.json, and rpminspect.dson local config files

### PR DESCRIPTION
**Pull request by dcantrell**
rpminspect 1.11 now supports configuration file formats in YAML, JSON, or DSON.  Local configuration files can be rpminspect.yaml, rpminspect.json, or rpminspect.dson.  Modify the runner scripts to support any of these existing in the git repos so they are present when the rpminspect job runs.  Package maintainers can now write their local config files in any of these formats.

### CODE REVIEW

**Comment by dcantrell** [comment]
@msrb there are dist-git repos that are now gaining rpminspect.json and rpminspect.dson files, so getting this one in sooner is going to be helpful for those projects.

**Comment by msrb** [comment]
Thanks for the pull request.

For testing purposes, do you remember which component(s) use the new formats already?

**Comment by dcantrell** [comment]
I've seen it in grub2 so far.

**Comment by msrb** [comment]
That is a strange file format :)
https://src.fedoraproject.org/rpms/grub2/blob/rawhide/f/rpminspect.dson

**Comment by msrb** [comment]
I am gonna push the update to Fedora CI now and let it run over the weekend. Downstream will follow on Monday ;)

**Comment by msrb** [comment]
Works!
https://artifacts.dev.testing-farm.io/83306b00-73ef-4e00-ba72-541e69b1585a/work-rpminspect6exbt0jr/rpminspect/execute/data/rpminspect/data/viewer.html
https://artifacts.dev.testing-farm.io/83306b00-73ef-4e00-ba72-541e69b1585a/work-rpminspect6exbt0jr/rpminspect/execute/data/rpminspect/data/verbose.log

**Pull request merged**
